### ISSUE TITLE
make tmpfile location handling more robust

### ISSUE THREAD

**Issue by tkellen** [tkellen/js-v8flags#13]
1. check if `require('os').tmpdir()` is actually a directory
2. if not, set it to the install path of this module
3. if the temp file fails to write, throw with an error message that clearly indicates what v8flags is, why the error occurred and possibly provide suggested steps to resolve.

/ref tkellen/js-liftoff#45

**Comment by orlin** [comment]
I pushed `gulp-npm-test` [once more](https://travis-ci.org/orlin/gulp-npm-test/builds/55396610) to illustrate that setting the `--gulpfile` doesn't help and to get the tmp location for you which is `/tmp`, as expected.

I can give you a failing test if you'd like to have gulp and [batshit](https://github.com/orlin/batshit) as `devDependencies` - batshit will use bats to to run gulp.  That would compete with mocha though.  And would be a temporary measure (batshit will never be supported on windows), and you could achieve the same by cloning `gulp-npm-test` on a linux and `npm link`ing the `js-v8flags`.  I also just encountered an issue with batshit that may cause it to fail on linux in some cases.  Not a problem with travis (as I use batshit to test other modules).  I'm guessing that you don't want neither gulp nor batshit to test this...

Or maybe some project that tests cli usage from an outside-of-node perspective?

**Comment by orlin** [comment]
Ok, I got the fail test done without extra dependencies.  The issue is with `bats` which changes `$TMP` to a dir that exists only temporarily.  For example if I create a `test/tmp` beforehand (in this case `./tmp`, then all is ok.  Make sure you test this with linux, because somehow it not a problem on a mac.

**Comment by tkellen** [comment]
resolved in cf81d5b6f801ad5c44c2559e21c636de69a6cdd9
