### ISSUE TITLE
gulp build up on AppVeyor

### ISSUE THREAD

**Issue by staxmanade** [tkellen/js-v8flags#17]
Hello,

I'm struggling to get a gulp build to run up on appveyor. The [following build](https://ci.appveyor.com/project/JasonJarrett/approvals-nodejs/build/44/job/6st31a35a9bdsds2) can show you the full example, for convenience I'm including the error below.

### Do you have any guidance on how to configure AppVeyor to work-around this error?

```
> approvals@0.0.25 test C:\projects\approvals-nodejs
> gulp
 
npm : C:\projects\approvals-nodejs\node_modules\gulp\node_modules\liftoff\index.js:171
At line:1 char:1
+ npm test --no-color
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\projects\app...ff\index.js:171:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
      throw err;
            ^
Error: EPERM, ftruncate
 
Unable to cache a config file for v8flags to a your home directory
or a temporary folder. To fix this problem, please correct your
environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
NOTE: the user running this must be able to access provided path.
If all else fails, please open an issue here:
http://github.com/tkellen/js-v8flags
    at Error (native)
 
npm
 ERR! Test failed.  See above for more details.
 
Command executed with exception:  ERR! Test failed.  See above for more details.

```

**Comment by RPM1984** [comment]
+1 same error today (all of a sudden)

**Comment by bryanwood** [comment]
:+1:

**Comment by PureKrome** [comment]
@tkellen - having problems here toooooo

/me goes back to watching the Star Wars trailer and crying while builds are broken.

**Comment by tkellen** [comment]
Will have a fix up in a moment.

**Comment by ejsmith** [comment]
Any update on this?

**Comment by tkellen** [comment]
I may revert as this is breaking existing builds and the problem it meant to fix seems less widespread. It would be helpful if someone on a windows machine could provide a patch. Appveyor takes like 10 minutes to run a build.  The reason I didn't catch this is because I recently renamed this from node-v8flags to js-v8flags and appveyor didn't automatically update, so I incorrectly thought it was passing.

**Comment by staxmanade** [comment]
Thanks for looking into this so quickly.

**Comment by PureKrome** [comment]
+1 @tkellen for looking into this also :) Much appreciated!

/me waits patiently for da magical fix.

**Comment by mmmeff** [comment]
Our build is broken as of this morning because of this, wahhhh

**Comment by tkellen** [comment]
try again ya'll.

**Comment by PureKrome** [comment]
OMG! ZOMG! ZOE-MAI-GAWD!

`it.works.again`.

![](http://i.giphy.com/MCKQEmHkUyGf6.gif)

![](http://giphy.com/gifs/my-little-pony-awesome-eEtxYul1kBS80)

![](http://giphy.com/gifs/xqrvSHPX14hAQ)

**Comment by staxmanade** [comment]
Thanks!

**Comment by huston8** [comment]
I am still facing this issue. I am using a CMS to deploy the gulp and less files. I am getting the error while compiling.

**Comment by tkellen** [comment]
@huston8 please open a new issue and post your log output.
