### ISSUE TITLE
Unable to cache a config file in home directory

### ISSUE THREAD

**Issue by balihoo-jflitton** [tkellen/js-v8flags#23]
Just started getting this error when running my tests on our CI server this morning:

15-Jun-2015 09:40:24	/mnt/software/bamboo/bamboo-data/xml-data/build-dir/RELEASEMGMT-BLIPDEVBUILD-JOB1/src/node_modules/gulp/node_modules/liftoff/index.js:182
15-Jun-2015 09:40:24	      throw err;
15-Jun-2015 09:40:24	            ^
15-Jun-2015 09:40:24	Error: ENOENT, open '/home/bamboo/.cache/.v8flags.3.14.5.9.bamboo.json'
15-Jun-2015 09:40:24	
15-Jun-2015 09:40:24	Unable to cache a config file for v8flags to a your home directory
15-Jun-2015 09:40:24	or a temporary folder. To fix this problem, please correct your
15-Jun-2015 09:40:24	environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
15-Jun-2015 09:40:24	NOTE: the user running this must be able to access provided path.
15-Jun-2015 09:40:24	If all else fails, please open an issue here:
15-Jun-2015 09:40:24	http://github.com/tkellen/js-v8flags
15-Jun-2015 09:40:24	
15-Jun-2015 09:40:24	Unable to cache a config file for v8flags to a your home directory
15-Jun-2015 09:40:24	or a temporary folder. To fix this problem, please correct your
15-Jun-2015 09:40:24	environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
15-Jun-2015 09:40:24	NOTE: the user running this must be able to access provided path.
15-Jun-2015 09:40:24	If all else fails, please open an issue here:
15-Jun-2015 09:40:24	http://github.com/tkellen/js-v8flags
15-Jun-2015 09:40:24	npm ERR! Test failed.  See above for more details.
15-Jun-2015 09:40:24	npm ERR! not ok code 0

I'm using gulp, which uses this project.  I don't have much control over the management of this CI environment, so I can't give the user access to this directory (or verify its existence) however I was under the impression that the package would use /tmp for this purpose failing write access to the home directory.  Let me know if there's anything more I can provide!

**Comment by tkellen** [comment]
Thanks for the heads up @balihoo-jflitton. I just released a patch fix and I'm going to investigate fixing this specific issue and the higher level issue of not even bailing if the cache can't be created. The only problem this really introduces is a slight performance hit on startup. We should log an error rather than outright failing here.
